services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  backend:
    build: ./backend
    environment:
      - ALLOW_MODEL_DOWNLOAD=0
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    ports:
      - '8000:8000'
    volumes:
      - ./data:/data
    depends_on:
      - redis

  celery-worker:
    build: ./backend
    environment:
      - ALLOW_MODEL_DOWNLOAD=0
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    volumes:
      - ./data:/data
    depends_on:
      - redis
      - backend
    command: python start_celery_worker.py

  celery-beat:
    build: ./backend
    environment:
      - ALLOW_MODEL_DOWNLOAD=0
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    volumes:
      - ./data:/data
      - celery_beat_data:/tmp
    depends_on:
      - redis
      - backend
    command: python start_celery_beat.py

  flower:
    build: ./backend
    environment:
      - ALLOW_MODEL_DOWNLOAD=0
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    ports:
      - '5555:5555'
    depends_on:
      - redis
      - celery-worker
    command: python start_flower.py

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  redis_data:
  celery_beat_data:
