global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Application metrics
  - job_name: 'financial-intelligence-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/admin/monitoring/metrics/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  # System metrics via node exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Celery metrics
  - job_name: 'celery'
    static_configs:
      - targets: ['flower:5555']
    metrics_path: '/api/workers'
    scrape_interval: 60s